/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ar.edu.unlar.paradigmas3.javavisual.gui.forms.gestionpersonas;


import ar.edu.unlar.paradigmas3.javavisual.gui.IFormularioControl;
import ar.edu.unlar.paradigmas3.javavisual.JavaVisual;
import ar.edu.unlar.paradigmas3.javavisual.gui.Principal;

/**
 *
 * @author sebas
 */
public class GestionPersona extends javax.swing.JInternalFrame implements IFormularioControl {

    private int filaseleccionada;

    /**
     * Creates new form GestionPersona
     */
    public GestionPersona() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personaController = new ar.edu.unlar.paradigmas3.javavisual.controladores.PersonaController();
        persona = new ar.edu.unlar.paradigmas3.javavisual.objects.Persona();
        grillaPersonas = new ar.edu.unlar.paradigmas3.javavisual.gui.forms.gestionpersonas.grillas.GrillaPersonas(JavaVisual.personas);
        jScrollPane1 = new javax.swing.JScrollPane();
        jtgrilla = new javax.swing.JTable();
        jbNuevo = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbCerrar = new javax.swing.JButton();

        jtgrilla.setModel(grillaPersonas);
        jScrollPane1.setViewportView(jtgrilla);

        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbCerrar.setText("Cerrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbCerrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevo)
                    .addComponent(jbModificar)
                    .addComponent(jbEliminar)
                    .addComponent(jbCerrar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        filaseleccionada=jtgrilla.getSelectedRow();
        persona=JavaVisual.personas.get(filaseleccionada);
        showAbm(2);        // TODO add your handling code here:
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        showAbm(1);
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        showAbm(3);
    }//GEN-LAST:event_jbEliminarActionPerformed

    @Override
    public void showAbm(int accion) {
        // TODO add your handling code here:
        AbmPersona abmPersona=new AbmPersona(accion, persona,this);
        Principal.desktopPane.add(abmPersona);
        abmPersona.setVisible(true);
    }
    
    @Override
    public void refrescarGrilla(){
        grillaPersonas.fireTableDataChanged();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ar.edu.unlar.paradigmas3.javavisual.gui.forms.gestionpersonas.grillas.GrillaPersonas grillaPersonas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCerrar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JTable jtgrilla;
    private ar.edu.unlar.paradigmas3.javavisual.objects.Persona persona;
    private ar.edu.unlar.paradigmas3.javavisual.controladores.PersonaController personaController;
    // End of variables declaration//GEN-END:variables
}
